server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_ecommerce
    username: root
    password: 314159
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: order-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
      topic.name: order-topic
      properties:
        spring.json.type.mapping: order-event:com.example.order.service.entity.OrderEvent,order:com.example.order.service.entity.Order
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted.packages: "*"
            type.mapping: order-confirm-event:com.example.order.service.entity.OrderEvent
      topic.name: order-confirm
      group-id: inventory